// Generated by tools/generate-editor-descriptor.mjs from the canonical schema.
// UI metadata only; this file is not financial execution authority.
export const PERSONAL_EDITOR_DESCRIPTOR = {
  "Household": {
    "collection": "Household",
    "idField": "household_id",
    "fields": {
      "household_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "name": {
        "type": "string",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "household_type": {
        "type": "enum",
        "required": true,
        "default": "individual",
        "enum": "household_type",
        "enumValues": [
          "individual",
          "couple",
          "family",
          "other"
        ],
        "derived": false,
        "mutable": true
      },
      "formation_date": {
        "type": "date",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "dissolution_date": {
        "type": "date",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "members": {
        "type": "uuid[]",
        "required": true,
        "default": null,
        "ref": "Person",
        "derived": false,
        "mutable": true
      },
      "primary_jurisdiction": {
        "type": "jurisdiction",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "filing_status": {
        "type": "enum",
        "required": false,
        "default": null,
        "enum": "filing_status",
        "enumValues": [
          "single",
          "married_joint",
          "married_separate",
          "head_of_household",
          "qualifying_widow_er"
        ],
        "derived": true,
        "mutable": true
      },
      "household_income": {
        "type": "money",
        "required": false,
        "default": null,
        "derived": true,
        "mutable": false
      },
      "household_expenses": {
        "type": "money",
        "required": false,
        "default": null,
        "derived": true,
        "mutable": false
      },
      "household_net_worth": {
        "type": "money",
        "required": false,
        "default": null,
        "derived": true,
        "mutable": false
      }
    }
  },
  "Person": {
    "collection": "Person",
    "idField": "person_id",
    "fields": {
      "person_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "first_name": {
        "type": "string",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "last_name": {
        "type": "string",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "date_of_birth": {
        "type": "date",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "date_of_death": {
        "type": "date",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "household_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "Household",
        "derived": false,
        "mutable": true
      },
      "relationship_status": {
        "type": "enum",
        "required": false,
        "default": "single",
        "enum": "person_relationship_status",
        "enumValues": [
          "single",
          "married",
          "partnered",
          "divorced",
          "widowed",
          "other"
        ],
        "derived": false,
        "mutable": true
      },
      "employment_status": {
        "type": "enum",
        "required": true,
        "default": "employed",
        "enum": "employment_status",
        "enumValues": [
          "employed",
          "unemployed",
          "retired",
          "self_employed",
          "student",
          "other"
        ],
        "derived": false,
        "mutable": true
      },
      "residence_jurisdiction": {
        "type": "jurisdiction",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "filing_status": {
        "type": "enum",
        "required": false,
        "default": null,
        "enum": "filing_status",
        "enumValues": [
          "single",
          "married_joint",
          "married_separate",
          "head_of_household",
          "qualifying_widow_er"
        ],
        "derived": true,
        "mutable": true
      },
      "life_expectancy": {
        "type": "decimal",
        "required": false,
        "default": null,
        "unit": "years",
        "derived": false,
        "mutable": true
      },
      "risk_profile": {
        "type": "string",
        "required": false,
        "default": "moderate",
        "derived": false,
        "mutable": true
      }
    }
  },
  "Account": {
    "collection": "Account",
    "idField": "account_id",
    "fields": {
      "account_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "name": {
        "type": "string",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "account_type": {
        "type": "enum",
        "required": true,
        "default": "cash",
        "enum": "account_type",
        "enumValues": [
          "checking",
          "savings",
          "cash",
          "taxable_brokerage",
          "traditional_401k",
          "roth_401k",
          "traditional_ira",
          "roth_ira",
          "hsa",
          "hsa_investment",
          "529",
          "403b",
          "457b",
          "sep_ira",
          "simple_ira",
          "pension",
          "cash_value_insurance",
          "other"
        ],
        "derived": false,
        "mutable": false
      },
      "owner_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "ref": "Person|Household",
        "derived": false,
        "mutable": true
      },
      "institution": {
        "type": "string",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "currency": {
        "type": "currency",
        "required": true,
        "default": "USD",
        "derived": false,
        "mutable": false
      },
      "opening_date": {
        "type": "date",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "closing_date": {
        "type": "date",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "opening_balance": {
        "type": "money",
        "required": true,
        "default": "0.0000",
        "derived": false,
        "mutable": false
      },
      "current_balance": {
        "type": "money",
        "required": true,
        "default": "opening_balance",
        "derived": true,
        "mutable": true
      },
      "liquidity_class": {
        "type": "enum",
        "required": true,
        "default": "liquid",
        "enum": "liquidity_class",
        "enumValues": [
          "liquid",
          "semi_liquid",
          "illiquid",
          "restricted"
        ],
        "derived": false,
        "mutable": true
      },
      "tax_treatment": {
        "type": "enum",
        "required": true,
        "default": "taxable",
        "enum": "tax_treatment",
        "enumValues": [
          "taxable",
          "tax_deferred",
          "tax_free",
          "mixed",
          "inherited"
        ],
        "derived": false,
        "mutable": false
      },
      "contribution_limit_rule_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "TaxRule",
        "derived": false,
        "mutable": true
      },
      "withdrawal_rule_ids": {
        "type": "uuid[]",
        "required": false,
        "default": [],
        "ref": "TaxRule",
        "derived": false,
        "mutable": true
      },
      "fee_rule_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "TaxRule",
        "derived": false,
        "mutable": true
      },
      "return_model_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "PrimitiveInstance",
        "derived": false,
        "mutable": true
      },
      "transaction_ids": {
        "type": "uuid[]",
        "required": false,
        "default": [],
        "ref": "Transaction",
        "derived": false,
        "mutable": false
      }
    }
  },
  "Income": {
    "collection": "Income",
    "idField": "income_id",
    "fields": {
      "income_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "owner_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "ref": "Person|Household",
        "derived": false,
        "mutable": true
      },
      "income_type": {
        "type": "enum",
        "required": true,
        "default": "salary",
        "enum": "income_type",
        "enumValues": [
          "salary",
          "bonus",
          "commission",
          "overtime",
          "equity_compensation",
          "business",
          "rental",
          "interest",
          "dividend",
          "capital_gain",
          "pension",
          "social_security",
          "government_benefit",
          "unemployment",
          "severance",
          "gift",
          "inheritance",
          "other"
        ],
        "derived": false,
        "mutable": false
      },
      "source": {
        "type": "string",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "amount": {
        "type": "money",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "frequency": {
        "type": "enum",
        "required": true,
        "default": "annual",
        "enum": "payment_frequency",
        "enumValues": [
          "daily",
          "weekly",
          "biweekly",
          "semimonthly",
          "monthly",
          "bimonthly",
          "quarterly",
          "semiannual",
          "annual",
          "irregular"
        ],
        "derived": false,
        "mutable": true
      },
      "start_date": {
        "type": "date",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "end_date": {
        "type": "date",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "growth_model_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "PrimitiveInstance",
        "derived": false,
        "mutable": true
      },
      "probability_model_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "PrimitiveInstance",
        "derived": false,
        "mutable": true
      },
      "tax_character": {
        "type": "enum",
        "required": true,
        "default": "ordinary",
        "enum": "income_tax_character",
        "enumValues": [
          "ordinary",
          "qualified_dividend",
          "short_term_capital_gain",
          "long_term_capital_gain",
          "tax_free",
          "deferred",
          "other"
        ],
        "derived": false,
        "mutable": true
      },
      "gross_or_net": {
        "type": "string",
        "required": true,
        "default": "gross",
        "derived": false,
        "mutable": true
      },
      "related_event_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "Event",
        "derived": false,
        "mutable": true
      }
    }
  },
  "Expense": {
    "collection": "Expense",
    "idField": "expense_id",
    "fields": {
      "expense_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "owner_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "ref": "Person|Household",
        "derived": false,
        "mutable": true
      },
      "category": {
        "type": "string",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "amount": {
        "type": "money",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "frequency": {
        "type": "enum",
        "required": true,
        "default": "monthly",
        "enum": "payment_frequency",
        "enumValues": [
          "daily",
          "weekly",
          "biweekly",
          "semimonthly",
          "monthly",
          "bimonthly",
          "quarterly",
          "semiannual",
          "annual",
          "irregular"
        ],
        "derived": false,
        "mutable": true
      },
      "start_date": {
        "type": "date",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "end_date": {
        "type": "date",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "growth_model_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "PrimitiveInstance",
        "derived": false,
        "mutable": true
      },
      "essentiality": {
        "type": "enum",
        "required": false,
        "default": "discretionary",
        "enum": "expense_essentiality",
        "enumValues": [
          "essential",
          "discretionary"
        ],
        "derived": false,
        "mutable": true
      },
      "tax_deductibility_rule_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "TaxRule",
        "derived": false,
        "mutable": true
      },
      "payment_account_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "Account",
        "derived": false,
        "mutable": true
      },
      "event_trigger_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "Event",
        "derived": false,
        "mutable": true
      }
    }
  },
  "Asset": {
    "collection": "Asset",
    "idField": "asset_id",
    "fields": {
      "asset_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "name": {
        "type": "string",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "asset_type": {
        "type": "enum",
        "required": true,
        "default": "other",
        "enum": "asset_type",
        "enumValues": [
          "cash",
          "investment",
          "real_estate",
          "vehicle",
          "business",
          "personal_property",
          "other"
        ],
        "derived": false,
        "mutable": false
      },
      "owner_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "ref": "Person|Household",
        "derived": false,
        "mutable": true
      },
      "account_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "Account",
        "derived": false,
        "mutable": true
      },
      "acquisition_date": {
        "type": "date",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "acquisition_cost": {
        "type": "money",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "current_value": {
        "type": "money",
        "required": true,
        "default": "acquisition_cost",
        "derived": true,
        "mutable": true
      },
      "valuation_method": {
        "type": "enum",
        "required": true,
        "default": "market",
        "enum": "valuation_method",
        "enumValues": [
          "market",
          "appraisal",
          "cost",
          "formula",
          "custom"
        ],
        "derived": false,
        "mutable": true
      },
      "appreciation_model_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "PrimitiveInstance",
        "derived": false,
        "mutable": true
      },
      "depreciation_model_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "PrimitiveInstance",
        "derived": false,
        "mutable": true
      },
      "sale_date": {
        "type": "date",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "sale_cost": {
        "type": "money",
        "required": false,
        "default": "0.0000",
        "derived": false,
        "mutable": true
      },
      "tax_basis": {
        "type": "money",
        "required": false,
        "default": "acquisition_cost",
        "derived": true,
        "mutable": true
      },
      "liquidity_class": {
        "type": "enum",
        "required": true,
        "default": "illiquid",
        "enum": "liquidity_class",
        "enumValues": [
          "liquid",
          "semi_liquid",
          "illiquid",
          "restricted"
        ],
        "derived": false,
        "mutable": true
      }
    }
  },
  "Liability": {
    "collection": "Liability",
    "idField": "liability_id",
    "fields": {
      "liability_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "name": {
        "type": "string",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "liability_type": {
        "type": "enum",
        "required": true,
        "default": "other",
        "enum": "liability_type",
        "enumValues": [
          "mortgage",
          "auto",
          "student",
          "credit_card",
          "personal",
          "heloc",
          "business",
          "tax",
          "other"
        ],
        "derived": false,
        "mutable": false
      },
      "owner_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "ref": "Person|Household",
        "derived": false,
        "mutable": true
      },
      "principal": {
        "type": "money",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "current_balance": {
        "type": "money",
        "required": true,
        "default": "principal",
        "derived": false,
        "mutable": true
      },
      "interest_rate": {
        "type": "rate",
        "required": true,
        "default": "0.0",
        "derived": false,
        "mutable": true
      },
      "rate_type": {
        "type": "enum",
        "required": true,
        "default": "fixed",
        "enum": "rate_type",
        "enumValues": [
          "fixed",
          "variable",
          "indexed"
        ],
        "derived": false,
        "mutable": true
      },
      "payment_frequency": {
        "type": "enum",
        "required": true,
        "default": "monthly",
        "enum": "payment_frequency",
        "enumValues": [
          "daily",
          "weekly",
          "biweekly",
          "semimonthly",
          "monthly",
          "bimonthly",
          "quarterly",
          "semiannual",
          "annual",
          "irregular"
        ],
        "derived": false,
        "mutable": true
      },
      "scheduled_payment": {
        "type": "money",
        "required": false,
        "default": null,
        "derived": true,
        "mutable": true
      },
      "minimum_payment": {
        "type": "money",
        "required": false,
        "default": "0.0000",
        "derived": true,
        "mutable": true
      },
      "extra_payment": {
        "type": "money",
        "required": false,
        "default": "0.0000",
        "derived": false,
        "mutable": true
      },
      "origination_date": {
        "type": "date",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "maturity_date": {
        "type": "date",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "amortization_model_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "PrimitiveInstance",
        "derived": false,
        "mutable": true
      },
      "fee_rule_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "TaxRule",
        "derived": false,
        "mutable": true
      },
      "prepayment_rule_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "TaxRule",
        "derived": false,
        "mutable": true
      },
      "collateral_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "Asset",
        "derived": false,
        "mutable": true
      },
      "tax_treatment": {
        "type": "enum",
        "required": false,
        "default": "taxable",
        "enum": "tax_treatment",
        "enumValues": [
          "taxable",
          "tax_deferred",
          "tax_free",
          "mixed",
          "inherited"
        ],
        "derived": false,
        "mutable": true
      }
    }
  },
  "Investment": {
    "collection": "Investment",
    "idField": "investment_id",
    "fields": {
      "investment_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "account_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "ref": "Account",
        "derived": false,
        "mutable": true
      },
      "asset_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "Asset",
        "derived": false,
        "mutable": true
      },
      "investment_type": {
        "type": "enum",
        "required": true,
        "default": "equity",
        "enum": "investment_type",
        "enumValues": [
          "equity",
          "bond",
          "fund",
          "cash",
          "real_estate",
          "option",
          "commodity",
          "crypto",
          "other"
        ],
        "derived": false,
        "mutable": true
      },
      "symbol": {
        "type": "string",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "quantity": {
        "type": "decimal",
        "required": true,
        "default": "0.0000",
        "derived": false,
        "mutable": true
      },
      "price": {
        "type": "money",
        "required": true,
        "default": "0.0000",
        "derived": true,
        "mutable": true
      },
      "market_value": {
        "type": "money",
        "required": true,
        "default": "0.0000",
        "derived": true,
        "mutable": true
      },
      "expected_return": {
        "type": "rate",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "volatility": {
        "type": "rate",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "contribution_model_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "PrimitiveInstance",
        "derived": false,
        "mutable": true
      },
      "return_model_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "PrimitiveInstance",
        "derived": false,
        "mutable": true
      },
      "tax_treatment": {
        "type": "enum",
        "required": true,
        "default": "inherited",
        "enum": "tax_treatment",
        "enumValues": [
          "taxable",
          "tax_deferred",
          "tax_free",
          "mixed",
          "inherited"
        ],
        "derived": false,
        "mutable": true
      },
      "rebalancing_rule_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "Rule",
        "derived": false,
        "mutable": true
      }
    }
  },
  "Assumption": {
    "collection": "Assumption",
    "idField": "assumption_id",
    "fields": {
      "assumption_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "name": {
        "type": "string",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "category": {
        "type": "enum",
        "required": true,
        "default": "other",
        "enum": "assumption_category",
        "enumValues": [
          "inflation",
          "market_return",
          "salary_growth",
          "longevity",
          "healthcare",
          "tax",
          "housing",
          "employment",
          "demographic",
          "interest_rate",
          "expense_growth",
          "education",
          "insurance",
          "other"
        ],
        "derived": false,
        "mutable": true
      },
      "value": {
        "type": "decimal",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "unit": {
        "type": "string",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "start_date": {
        "type": "date",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "end_date": {
        "type": "date",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "distribution_type": {
        "type": "enum",
        "required": false,
        "default": null,
        "enum": "distribution_type",
        "enumValues": [
          "normal",
          "lognormal",
          "uniform",
          "triangular",
          "discrete",
          "empirical",
          "mixture",
          "custom"
        ],
        "derived": false,
        "mutable": true
      },
      "distribution_parameters": {
        "type": "object",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "correlation_group": {
        "type": "string",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "source": {
        "type": "enum",
        "required": true,
        "default": "user",
        "enum": "source_type",
        "enumValues": [
          "user",
          "historical",
          "external",
          "model"
        ],
        "derived": false,
        "mutable": true
      },
      "confidence": {
        "type": "rate",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "scenario_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "ref": "Scenario",
        "derived": false,
        "mutable": false
      }
    }
  },
  "Scenario": {
    "collection": "Scenario",
    "idField": "scenario_id",
    "fields": {
      "scenario_id": {
        "type": "uuid",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "name": {
        "type": "string",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "description": {
        "type": "string",
        "required": false,
        "default": null,
        "derived": false,
        "mutable": true
      },
      "base_scenario_id": {
        "type": "uuid",
        "required": false,
        "default": null,
        "ref": "Scenario",
        "derived": false,
        "mutable": false
      },
      "start_date": {
        "type": "date",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "end_date": {
        "type": "date",
        "required": true,
        "default": null,
        "derived": false,
        "mutable": false
      },
      "timestep": {
        "type": "enum",
        "required": true,
        "default": "monthly",
        "enum": "timestep",
        "enumValues": [
          "daily",
          "monthly",
          "quarterly",
          "annual"
        ],
        "derived": false,
        "mutable": false
      },
      "assumption_ids": {
        "type": "uuid[]",
        "required": false,
        "default": [],
        "ref": "Assumption",
        "derived": false,
        "mutable": true
      },
      "event_ids": {
        "type": "uuid[]",
        "required": false,
        "default": [],
        "ref": "Event",
        "derived": false,
        "mutable": true
      },
      "enabled": {
        "type": "boolean",
        "required": true,
        "default": true,
        "derived": false,
        "mutable": true
      },
      "stochastic": {
        "type": "boolean",
        "required": true,
        "default": false,
        "derived": false,
        "mutable": true
      },
      "simulation_count": {
        "type": "integer",
        "required": false,
        "default": 1,
        "derived": false,
        "mutable": true
      }
    }
  }
} as const;
